apiVersion: v1
kind: Service
metadata:
  name: istio-eastwestgateway
  namespace: istio-system
  labels:
    app: istio-eastwestgateway
    app.kubernetes.io/instance: istio-eastwestgateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-eastwestgateway
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 1.27.2
    helm.sh/chart: gateway-1.27.2
    istio: eastwestgateway
    istio.io/dataplane-mode: none
    topology.istio.io/network: network3
  annotations:
    meta.helm.sh/release-name: istio-eastwestgateway
    meta.helm.sh/release-namespace: istio-system
spec:
  type: NodePort
  selector:
    app: istio-eastwestgateway
    istio: eastwestgateway
  ports:
    - name: status-port
      protocol: TCP
      port: 15021
      targetPort: 15021
      nodePort: 32185
    - name: tls
      protocol: TCP
      port: 15443
      targetPort: 15443
      nodePort: 30930
    - name: tls-istiod
      protocol: TCP
      port: 15012
      targetPort: 15012
      nodePort: 31048
    - name: tls-webhook
      protocol: TCP
      port: 15017
      targetPort: 15017
      nodePort: 30260
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
