apiVersion: v1
kind: Pod
metadata:
  name: mmt-probe-restore
  annotations:
    io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel: "true"
  labels:
    app: routing-demo
    version: v2-monitor
spec:
  containers:
    - name: mmt-probe-restore
      image: 160.85.255.146:5000/mmt-probe:checkpoint
      imagePullPolicy: Always
      securityContext:
        seLinuxOptions:
          level: s0:c0
